In [3]:
from dataset import GTSequenceDataset
from torch.utils.data import DataLoader, ConcatDataset

SEQ_IN_LEN = 30
SEQ_OUT_LEN = 20
SEQ_TOTAL_LEN = 50
BATCH_SIZE = 512
STEPS = 4
NOISE_COEFFICIENT = 0.15
NOISE_PROB = 0.4

BASE_DIR = '../../Datasets/'
# train_dataset = ConcatDataset([
#     GTSequenceDataset.from_roots([f'{BASE_DIR}DanceTrack/train'], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB),
#     GTSequenceDataset.from_roots([f'{BASE_DIR}MOT20/train'], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB),
#     GTSequenceDataset.from_roots([f'{BASE_DIR}MOT17/train'], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB),
# ])
# val_dataset = ConcatDataset([
#     GTSequenceDataset.from_roots([f'{BASE_DIR}DanceTrack/val'], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB),
#     GTSequenceDataset.from_roots([f'{BASE_DIR}MOT20/val'], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB),
#     GTSequenceDataset.from_roots([f'{BASE_DIR}MOT17/val'], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB),
# ])
train_dataset = GTSequenceDataset.from_roots([
    f'{BASE_DIR}/SportsMOT/train',
    f'{BASE_DIR}DanceTrack/train',
    f'{BASE_DIR}MOT17/train',
    f'{BASE_DIR}MOT20/train'
], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB)

val_dataset = GTSequenceDataset.from_roots([
    f'{BASE_DIR}/SportsMOT/val',
    f'{BASE_DIR}DanceTrack/val',
    f'{BASE_DIR}MOT17/val',
    f'{BASE_DIR}MOT20/val'
], seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, steps=STEPS, noise_coeff=NOISE_COEFFICIENT, noise_prob=NOISE_PROB)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=True)

print(f'Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}')

../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 0
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 1
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 2
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 3
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 4
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 5
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 6
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 7
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 8
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 9
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 10
../../Datasets//SportsMOT/train/v_Dk3EpDDa3o0_c002 11
../../Datasets//SportsMOT/train/v_4LXTUim5anY_c012 0
../../Datasets//SportsMOT/train/v_4LXTUim5anY_c012 1
../../Datasets//SportsMOT/train/v_4LXTUim5anY_c012 2
../../Datasets//SportsMOT/train/v_4LXTUim5anY_c012 3
../../Datasets//SportsMOT/train/v_4LXTUim5anY_c012 4
../../Datasets//SportsMOT/train/v_4LXTUim5anY_c012 5
../../Datasets//SportsMOT/train/v_4LXTUim5an

../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 3
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 4
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 5
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 6
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 7
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 8
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 9
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 10
../../Datasets//SportsMOT/train/v_CW0mQbgYIF4_c006 11
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 0
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 1
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 2
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 3
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 4
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 5
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 6
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 7
../../Datasets//SportsMOT/train/v_ApPxnw_Jffg_c009 8
../../Datasets//SportsMOT/train/v_ApPxnw_Jff

In [5]:
d = next(iter(train_loader))

In [16]:
d[1][:, :, -1].reshape(-1)


tensor([0.7066, 1.0000, 0.9401,  ..., 0.6589, 1.0000, 0.8530])

In [8]:
from transformer_encoder import MotionTransformer
from loss import LossFunction
from torch import optim
import math, torch, torch.nn as nn
import torch.nn.functional as F
import random
import os


DEVICE = 'cuda'
model = MotionTransformer(
    input_dim=13,
    output_dim=5,
    d_model=256,
    nhead=16,
    num_layers=6,
    dim_ff=512,
    dropout=0.1,
).to(DEVICE)
criterion = LossFunction(loss1_coeff=0.5, loss2_coeff=0, loss3_coeff=0.5, loss4_coeff=0)
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")


Model parameters: 3,247,621


In [9]:
model.load_weight('pretrained/transformer-encoder-d256-ff512-6l-ft.pth')
# model.load_weight('pretrained/transformer-encoder-d512-ff512-2l-ft.pth')
# model.load_weight('pretrained/transformer-encoder-d512-ff512-6l.pth')

In [7]:
model.evaluate(val_loader, criterion)

0.0200511137092555

In [10]:
criterion1 = LossFunction(loss1_coeff=0, loss2_coeff=1, loss3_coeff=0, loss4_coeff=0)
criterion2 = LossFunction(loss1_coeff=0, loss2_coeff=0, loss3_coeff=0, loss4_coeff=0)


In [6]:
model.evaluate(val_loader, criterion1)

NameError: name 'criterion1' is not defined

In [ ]:
LR = 1e-5
NUM_EPOCHS = 20

optimizer = optim.AdamW(
    model.parameters(),
    lr=LR,
    betas=(0.9, 0.999),
    weight_decay=1e-4,
    eps=1e-8
)
# scheduler = optim.lr_scheduler.ReduceLROnPlateau(
#         optimizer,
#         mode='min',
#         factor=0.5,
#         patience= 11,  # Reduce LR before early stopping
#         verbose=True,
#         min_lr=LR * 0.001
#     )
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS + 1)
best_val_loss = float("inf")
log_file = open('file.log', 'w')
log_file.close()

for epoch in range(1, NUM_EPOCHS + 1):
    train_loss = model.train_one_epoch(train_loader, optimizer, criterion)
    val_loss = model.evaluate(val_loader, criterion)

    scheduler.step()

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        model.save_weight('pretrained/transformer-encoder-d256-ff512-6l-ft2.pth')

    current_lr = scheduler.get_last_lr()[0]
    print(f"Epoch {epoch}: Train Loss = {train_loss:.8f}, Val Loss = {val_loss:.8f}, LR = {current_lr:.8f}")
    log_file = open('file.log', 'a')
    log_file.write(f"Epoch {epoch}: Train Loss = {train_loss:.8f}, Val Loss = {val_loss:.8f}, LR = {current_lr:.8f}\n")
    log_file.close()

print("Training complete. Best Val Loss:", best_val_loss)

Epoch 1: Train Loss = 0.04527373, Val Loss = 0.04408624, LR = 0.00000994
Epoch 2: Train Loss = 0.04390956, Val Loss = 0.04346136, LR = 0.00000978
Epoch 3: Train Loss = 0.04320474, Val Loss = 0.04317352, LR = 0.00000950
Epoch 4: Train Loss = 0.04268039, Val Loss = 0.04282973, LR = 0.00000913
Epoch 5: Train Loss = 0.04226573, Val Loss = 0.04277668, LR = 0.00000867
Epoch 6: Train Loss = 0.04194911, Val Loss = 0.04242086, LR = 0.00000812
Epoch 7: Train Loss = 0.04168984, Val Loss = 0.04237355, LR = 0.00000750
Epoch 8: Train Loss = 0.04149238, Val Loss = 0.04227028, LR = 0.00000683
Epoch 9: Train Loss = 0.04132704, Val Loss = 0.04224452, LR = 0.00000611
Epoch 10: Train Loss = 0.04118590, Val Loss = 0.04216746, LR = 0.00000537
Epoch 11: Train Loss = 0.04107759, Val Loss = 0.04208273, LR = 0.00000463
Epoch 12: Train Loss = 0.04097707, Val Loss = 0.04206226, LR = 0.00000389


In [15]:
log_file = open('file.log', 'w')
log_file.close()

In [6]:
# model.save_weight('pretrained/transformer-encoder-d256-ff512-2l-test2.pth')
model.load_weight('pretrained/transformer-encoder-d512-ff512-2l.pth')
# model.load_weight('pretrained/transformer-encoder-d256-ff512-2l-test2.pth')

In [26]:
# a, b, c, d = next(iter(train_loader))
a, b, c, d = next(iter(val_loader))
a = a.cuda()
b = b.cuda()
c = c.cuda()
d = d.cuda()
o = model.forward(a, b[:, :-1])[13]

In [27]:
o[:, 4]

tensor([0.9558, 0.9005, 0.8820, 0.9544, 0.9547, 0.8981, 0.9098, 0.9404, 0.9516,
        0.9479, 0.9433, 0.9555, 0.9543, 0.8426, 0.7750, 0.9360, 0.9307, 0.9547,
        0.8936], device='cuda:0', grad_fn=<SelectBackward0>)

In [7]:
g = torch.tensor([[[0.1976, 0.0841, 0.0298, 0.0943]]]).cuda()
h = torch.tensor([[[0.1991, 0.0818, 0.0281, 0.0977]]]).cuda()

criterion.iou(g, h)

tensor([[[0.8621]]], device='cuda:0')

In [8]:
torch.diagonal(criterion.iou(d[:, :, :4], o[:, :, :4]), dim1=1, dim2=2).mean()

IndexError: too many indices for tensor of dimension 2

In [28]:
o[:, :4]

tensor([[0.9575, 0.5110, 0.1029, 0.5032],
        [0.9559, 0.5075, 0.1033, 0.5064],
        [0.9528, 0.5099, 0.1099, 0.5171],
        [0.9525, 0.5109, 0.1050, 0.5094],
        [0.9498, 0.5103, 0.1050, 0.5105],
        [0.9488, 0.5099, 0.1054, 0.5174],
        [0.9466, 0.5103, 0.1130, 0.5205],
        [0.9447, 0.5102, 0.1065, 0.5176],
        [0.9431, 0.5099, 0.1066, 0.5209],
        [0.9424, 0.5108, 0.1062, 0.5230],
        [0.9407, 0.5100, 0.1068, 0.5272],
        [0.9393, 0.5108, 0.1069, 0.5307],
        [0.9369, 0.5101, 0.1078, 0.5337],
        [0.9388, 0.5120, 0.0958, 0.5335],
        [0.9360, 0.5452, 0.1075, 0.6517],
        [0.9332, 0.5168, 0.1076, 0.5479],
        [0.9327, 0.5124, 0.1073, 0.5609],
        [0.9310, 0.5115, 0.1080, 0.5481],
        [0.9290, 0.5155, 0.1078, 0.5604]], device='cuda:0',
       grad_fn=<SliceBackward0>)

In [29]:
d[13, 1:, :4]

tensor([[0.9573, 0.5102, 0.1031, 0.5019],
        [0.9555, 0.5102, 0.1036, 0.5037],
        [0.9536, 0.5102, 0.1042, 0.5074],
        [0.9518, 0.5102, 0.1047, 0.5093],
        [0.9500, 0.5097, 0.1052, 0.5120],
        [0.9482, 0.5097, 0.1057, 0.5139],
        [0.9464, 0.5102, 0.1063, 0.5167],
        [0.9448, 0.5097, 0.1063, 0.5194],
        [0.9432, 0.5102, 0.1063, 0.5222],
        [0.9419, 0.5102, 0.1068, 0.5259],
        [0.9404, 0.5106, 0.1068, 0.5287],
        [0.9391, 0.5106, 0.1073, 0.5324],
        [0.9375, 0.5111, 0.1073, 0.5352],
        [0.9359, 0.5111, 0.1073, 0.5389],
        [0.9349, 0.5111, 0.1073, 0.5407],
        [0.9333, 0.5111, 0.1073, 0.5444],
        [0.9320, 0.5116, 0.1078, 0.5472],
        [0.9305, 0.5116, 0.1078, 0.5509],
        [0.9289, 0.5120, 0.1078, 0.5537]], device='cuda:0')

In [25]:
c[13, :, :4]

tensor([[0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0.1389],
        [0.1747, 0.0491, 0.0234, 0

In [ ]:
import torch
from torch import nn

class LossFunction(nn.Module):
    def __init__(self, loss1_coeff=1, loss2_coeff=1, loss3_coeff=1, loss4_coeff=0.5):
        super().__init__()
        self.loss1_coeff = loss1_coeff  # IOU loss
        self.loss2_coeff = loss2_coeff  # Bbox regression loss
        self.loss3_coeff = loss3_coeff  # Confidence loss
        self.loss4_coeff = loss4_coeff  # Motion features loss (velocity/acceleration)

    def xywh_to_tlbr(self, bb : torch.Tensor):
        x, y, w, h = bb.unbind(-1)
        t = x - w / 2
        l = y - h / 2
        b = x + w / 2
        r = y + h / 2
        return torch.stack([t, l, b, r], dim=-1)

    def iou(self, target_boxes : torch.Tensor, pred_boxes: torch.Tensor):
        target_boxes = self.xywh_to_tlbr(target_boxes.clone())
        pred_boxes = self.xywh_to_tlbr(pred_boxes.clone())
        # print('target', target_boxes)
        # print('pred', pred_boxes)
        bb1 = target_boxes.unsqueeze(2)        # (B, N, 1, 4)
        bb2 = pred_boxes.unsqueeze(1)      # (B, 1, N, 4)
        xx1 = torch.maximum(bb1[..., 0], bb2[..., 0])
        yy1 = torch.maximum(bb1[..., 1], bb2[..., 1])
        xx2 = torch.minimum(bb1[..., 2], bb2[..., 2])
        yy2 = torch.minimum(bb1[..., 3], bb2[..., 3])
        w = torch.clamp(xx2 - xx1, min=0)
        h = torch.clamp(yy2 - yy1, min=0)
        inter = w * h
        area1 = (bb1[..., 2] - bb1[..., 0]) * (bb1[..., 3] - bb1[..., 1])
        area2 = (bb2[..., 2] - bb2[..., 0]) * (bb2[..., 3] - bb2[..., 1])
        union = area1 + area2 - inter
        ious = inter / (union + 1e-7)  # Add epsilon to prevent division by zero
        return ious
        

    def forward(self, targets, preds):
        target_boxes = targets[:, :, :4]
        pred_boxes = preds[:, :, :4]
        ious = self.iou(target_boxes, pred_boxes)
        ious = torch.diagonal(ious, dim1=1, dim2=2)

        loss1 = nn.functional.smooth_l1_loss(torch.ones_like(ious), ious)
        loss2 = nn.functional.smooth_l1_loss(target_boxes, pred_boxes)
        
        target_cs = targets[:, :, 4]
        pred_cs = preds[:, :, 4]
        loss3 = nn.functional.smooth_l1_loss(ious, pred_cs)
        
        return self.loss1_coeff * loss1 + self.loss2_coeff * loss2 + self.loss3_coeff * loss3
    
ls = LossFunction()
ls.forward(d[:, 1:], o)

In [5]:
model.load_weight('pretrained/transformer-encoder-d256-ff512-2l-wm.pth')

RuntimeError: Error(s) in loading state_dict for MotionTransformer:
	size mismatch for in_fc.0.weight: copying a param with shape torch.Size([64, 13]) from checkpoint, the shape in current model is torch.Size([128, 13]).
	size mismatch for in_fc.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for in_fc.1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for in_fc.1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for in_fc.4.weight: copying a param with shape torch.Size([128, 64]) from checkpoint, the shape in current model is torch.Size([256, 128]).
	size mismatch for in_fc.4.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for in_fc.5.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for in_fc.5.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for in_fc.8.weight: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([512, 256]).
	size mismatch for in_fc.8.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for pos_enc.pe: copying a param with shape torch.Size([1, 5000, 256]) from checkpoint, the shape in current model is torch.Size([1, 5000, 512]).
	size mismatch for transformer.layers.0.self_attn.in_proj_weight: copying a param with shape torch.Size([768, 256]) from checkpoint, the shape in current model is torch.Size([1536, 512]).
	size mismatch for transformer.layers.0.self_attn.in_proj_bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1536]).
	size mismatch for transformer.layers.0.self_attn.out_proj.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for transformer.layers.0.self_attn.out_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.0.linear1.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for transformer.layers.0.linear2.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for transformer.layers.0.linear2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.0.norm1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.0.norm1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.0.norm2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.0.norm2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.1.self_attn.in_proj_weight: copying a param with shape torch.Size([768, 256]) from checkpoint, the shape in current model is torch.Size([1536, 512]).
	size mismatch for transformer.layers.1.self_attn.in_proj_bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1536]).
	size mismatch for transformer.layers.1.self_attn.out_proj.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for transformer.layers.1.self_attn.out_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.1.linear1.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for transformer.layers.1.linear2.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for transformer.layers.1.linear2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.1.norm1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.1.norm1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.1.norm2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.layers.1.norm2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.norm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for transformer.norm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for out_fc.0.weight: copying a param with shape torch.Size([128, 256]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for out_fc.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for out_fc.1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for out_fc.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for out_fc.4.weight: copying a param with shape torch.Size([64, 128]) from checkpoint, the shape in current model is torch.Size([128, 256]).
	size mismatch for out_fc.4.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for out_fc.5.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for out_fc.5.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for out_fc.8.weight: copying a param with shape torch.Size([5, 64]) from checkpoint, the shape in current model is torch.Size([5, 128]).

In [33]:
SEQ_PATH = '../../Datasets/MOT20/val/MOT20-01/'

d = GTSequenceDataset.from_sequence(SEQ_PATH, seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, noise_prob=0, noise_coeff=0)
d = DataLoader(d, batch_size=1028)

In [34]:
model.evaluate(val_loader, criterion)

5.642101988587847e-07

In [23]:
import torch
from dataset import GTSequenceDataset

# SEQ_PATH = '../../Datasets/MOT20/val/MOT20-01/'
# SEQ_PATH = '../../Datasets/MOT17/val/MOT17-05-FRCNN//'
# SEQ_PATH = '../../Datasets/DanceTrack/val/dancetrack0019//'
# SEQ_PATH = '../../Datasets/DanceTrack/train/dancetrack0006//'
SEQ_PATH = '../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004//'
SEQ_IN_LEN = 5
SEQ_OUT_LEN = 2
SEQ_TOTAL_LEN = 7
BATCH_SIZE = 512

d = GTSequenceDataset.from_sequence(SEQ_PATH, seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, noise_prob=0, noise_coeff=0)
# d = GTSequenceDataset.from_sequence(SEQ_PATH, seq_in_len=SEQ_IN_LEN, seq_out_len=SEQ_OUT_LEN, seq_total_len=SEQ_TOTAL_LEN, noise_prob=0.6, noise_coeff=2)
sources = torch.tensor(d.sources).to(DEVICE)[:BATCH_SIZE]
targets = torch.tensor(d.targets).to(DEVICE)[:BATCH_SIZE]
gt_sources = torch.tensor(d.gt_sources).to(DEVICE)[:BATCH_SIZE]
gt_targets = torch.tensor(d.gt_targets).to(DEVICE)[:BATCH_SIZE]

# o = model.inference(sources, targets, num_steps=targets.size(1) - 1)
o = model.forward(sources, targets[:, :-1])

o[:, :, 0] *= d.image_width.item()
o[:, :, 2] *= d.image_width.item()
o[:, :, 1] *= d.image_height.item()
o[:, :, 3] *= d.image_height.item()
targets[:, :, 0] *= d.image_width.item()
targets[:, :, 2] *= d.image_width.item()
targets[:, :, 1] *= d.image_height.item()
targets[:, :, 3] *= d.image_height.item()
t_ = targets[:, 1:, :4]
sources[:, :, 0] *= d.image_width.item()
sources[:, :, 2] *= d.image_width.item()
sources[:, :, 1] *= d.image_height.item()
sources[:, :, 3] *= d.image_height.item()
o_ = o[:, :, :4]

index = 9
# t[index], o[index]
# f = (t[index] - o[index]).abs()[:, 3].mean()
# torch.diagonal(criterion.iou(t, o), dim1=1, dim2=2).mean()
# criterion.iou(t_, o_).mean()
criterion.ciou(t_, o_).mean()
# f = (t_ - o_).abs().mean()
# f


../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 0
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 1
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 2
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 3
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 4
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 5
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 6
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 7
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 8
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 9
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 10
../../Datasets/SportsMOT/val/v_0kUtTtmLaJA_c004// 11


tensor(0.8668, device='cuda:0', grad_fn=<MeanBackward0>)

In [25]:
o[:, :, 4]

tensor([[0.8423],
        [0.7681],
        [0.9192],
        [0.8807],
        [0.9343],
        [0.9154],
        [0.8629],
        [0.9207],
        [0.7539],
        [0.8986],
        [0.8904],
        [0.9096],
        [0.9191],
        [0.8688],
        [0.9376],
        [0.8760],
        [0.9031],
        [0.9031],
        [0.9260],
        [0.9252],
        [0.8743],
        [0.8791],
        [0.9293],
        [0.8585],
        [0.7721],
        [0.7899],
        [0.9143],
        [0.8263],
        [0.9425],
        [0.9401],
        [0.9209],
        [0.9143],
        [0.9255],
        [0.9133],
        [0.9308],
        [0.9298],
        [0.8253],
        [0.9267],
        [0.9395],
        [0.9054],
        [0.9198],
        [0.9241],
        [0.8941],
        [0.8914],
        [0.9247],
        [0.9204],
        [0.9113],
        [0.7843],
        [0.9208],
        [0.7869],
        [0.9159],
        [0.9362],
        [0.8417],
        [0.8824],
        [0.7484],
        [0

In [15]:
a = torch.tensor(
    [
        [
            [10,10,10,10],
            [30,30,40,40],
        ],
        [
            [30,30,20,20],
            [30,30,20,20]
        ],
        [
            [50,50,10,10],
            [40,40,20,20]
        ]
    ],
)
b = torch.tensor(
    [
        [
            [10,10,10,10],
            [30,30,40,40],
        ],
        [
            [30,30,20,20],
            [30,30,20,20]
        ],
        [
            [50,50,10,10],
            [40,40,20,20]
        ]
    ],
)

criterion.ciou(a, b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
o[:, :, 4]

tensor([[0.9530, 0.9529, 0.9506,  ..., 0.9533, 0.9372, 0.9489],
        [0.9467, 0.9369, 0.9466,  ..., 0.9484, 0.9511, 0.9503],
        [0.9313, 0.9312, 0.9532,  ..., 0.9465, 0.9538, 0.9517],
        ...,
        [0.9353, 0.9356, 0.9521,  ..., 0.9350, 0.9516, 0.9487],
        [0.9476, 0.9325, 0.9464,  ..., 0.9505, 0.9500, 0.9492],
        [0.9500, 0.9363, 0.9282,  ..., 0.9484, 0.9337, 0.9365]],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [8]:
targets[:, :, 4]

tensor([[-0.0008,  0.0004],
        [ 0.0016,  0.0023],
        [ 0.0074,  0.0117],
        ...,
        [ 0.0020,  0.0012],
        [-0.0047, -0.0063],
        [ 0.0000,  0.0066]], device='cuda:0')

In [38]:
gt_sources[0][0]

tensor([0.4023, 0.4671, 0.0672, 0.2343, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 1.0000], device='cuda:0')